version: '2.1'
  
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
      - '443:443' # turn this on when certificate is set up
    restart: always
    volumes:
      - /data/docker/etc:/etc/nginx/certs # mount certificate directory
      - /var/run/docker.sock:/tmp/docker.sock:ro
    container_name: nginx-proxy
​
  openmrs-referenceapplication:
    restart: "always"
    image: openmrs/openmrs-reference-application-distro:2.10.0
    expose:
      - 8080
    container_name: openmrs
    env_file:
      - ./openmrs_env/openmrs.env # move those environment variables below into file openmrs.env (for example: DB_DATABASE=openmrs)
    environment:
      - VIRTUAL_HOST=openmrs.ihie.org # virtual host for nginx_https (later this should be hooked up with certificate)
      - "TZ=America/Indianapolis"
    volumes:
#      - /data/docker/run/openmrs:/usr/local/tomcat/.OpenMRS/
      - openmrs-referenceapplication-data:/usr/local/tomcat/.OpenMRS/
      - /usr/local/tomcat/.OpenMRS/modules/ # do not store modules in data
      - /usr/local/tomcat/.OpenMRS/owa/ # do not store owa in data
      - /data/docker/run/setenv.sh:/usr/local/tomcat/bin/setenv.sh
      - /data/docker/run/tomcat_log:/usr/local/tomcat/logs
​
volumes:
   openmrs-referenceapplication-data:
