version: "3.0"

services:
  mysql:
    image: mysql:5.6
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_bin --default-storage-engine=INNODB --max_allowed_packet=256M --innodb_log_file_size=2GB --transaction-isolation=READ-COMMITTED --binlog_format=row"
    environment:
      - MYSQL_DATABASE:${MYSQL_DB:-openmrs}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD:-Admin123}
      - MYSQL_USER:${MYSQL_USER:-openmrs}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD:-Admin123}
    env_file: dev.env
    healthcheck:
      test: "exit 0"
    volumes:
      # - "./dbdump: /docker-entrypoint-initdb.d #if you dont need to use a backup sql to initialize the database"
      - "mysql-data:/var/lib/mysql"

  openmrs-reference-application:
    depends_on:
      - mysql
    env_file: dev.env
    ports:
      - 8080:8080

volumes:
  mysql-data:
