version: "3.0"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /data/docker/etc:/etc/nginx/certs # mount certificate directory
      - /var/run/docker.sock:/tmp/docker.sock:ro
    container_name: nginx-proxy

  openmrs-reference-application:
    restart: "always"
    container_name: openmrs
    env_file: .staging.env
    expose:
      - 8080
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs/"]
      timeout: 20s
    volumes:
      - /data/tomcat/.OpenMRS/modules/ # do not store modules in data
      - /data/tomcat/.OpenMRS/owa/ # do not store owa in data
      # - /data/docker/run/setenv.sh:/usr/local/tomcat/bin/setenv.sh
      - /data/docker/run/tomcat_log:/usr/local/tomcat/logs
