version: "3.0"

services:
  mysql:
    image: mysql:5.6
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_bin --default-storage-engine=INNODB --max_allowed_packet=256M --innodb_log_file_size=2GB --transaction-isolation=READ-COMMITTED --binlog_format=row"
    env_file: .dev-db.env
    healthcheck:
      test: "exit 0"
    volumes:
      # - "./dbdump: /docker-entrypoint-initdb.d #if you dont need to use a backup sql to initialize the database"
      - "mysql-data:/var/lib/mysql"

  openmrs-reference-application:
    depends_on:
      - mysql
    env_file: .dev.env
    ports:
      - 8080:8080

volumes:
  mysql-data:
