version: "3.0"

services:
  openmrs-reference-application:
    image: openmrs/openmrs-reference-application-distro:2.10.0
    volumes:
      - ./configuration:/usr/local/tomcat/.OpenMRS/configuration
