version: "3.0"

services:
  mysql:
    env_file: .dev.env
    volumes:
      - ../local/initdb.d/:/docker-entrypoint-initdb.d
      - ../local/data/database:/var/lib/mysql
      - ../local/log/mysql:/var/log/mysql
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
